# Generated by Django 4.2.2 on 2023-06-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='webAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiroNome', models.CharField(max_length=255)),
                ('ultimoNome', models.CharField(max_length=255)),
            ],
        ),
    ]
