# Generated by Django 4.2.2 on 2023-06-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAnimal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webAnimal',
            name='data_acesso',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='webAnimal',
            name='telefone',
            field=models.IntegerField(null=True),
        ),
    ]
