# Generated by Django 4.2.2 on 2023-06-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAnimal', '0002_members_data_acesso_members_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webAnimal',
            name='data_acesso',
            field=models.DateField(null=True),
        ),
    ]
