# Generated by Django 4.2.2 on 2023-06-29 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webAnimal', '0003_alter_members_data_acesso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='webAnimal',
            new_name='Member',
        ),
    ]
