# Generated by Django 4.2.2 on 2023-07-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAnimal', '0004_rename_members_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
