# Generated by Django 4.2.2 on 2023-07-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAnimal', '0006_delete_myimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
