# Generated by Django 4.2.2 on 2023-07-01 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webAnimal', '0007_myimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyImages',
        ),
    ]
