# Generated by Django 4.2.2 on 2023-07-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAnimal', '0008_delete_myimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='webAnimal/static/bd_images')),
            ],
        ),
    ]
