# Generated by Django 4.2.2 on 2023-07-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAnimal', '0009_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='foto',
            field=models.ImageField(upload_to='bd_images/'),
        ),
    ]
