# Generated by Django 4.2.2 on 2023-07-07 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAnimal', '0010_alter_photo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='comentario',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='nome',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='foto',
            field=models.ImageField(upload_to='bd_images/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png'])]),
        ),
    ]
