# Generated by Django 4.2.2 on 2023-07-24 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAnimal', '0011_photo_comentario_photo_nome_alter_photo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='foto',
            field=models.ImageField(upload_to='bd_images/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
