# Generated by Django 4.2.2 on 2023-07-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAnimal', '0012_alter_photo_foto_alter_photo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='nome',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
